In [1]:
import numpy as np

claims = np.array([
    [12000, 15000, 18000],
    [10000, 13000, 17000],
    [9000, 11000, 16000]
])
print("Insurance Claims Data(INR): ", claims)

Insurance Claims Data(INR):  [[12000 15000 18000]
 [10000 13000 17000]
 [ 9000 11000 16000]]


In [2]:
claims[2,0]

np.int64(9000)

In [3]:
total_claims = np.sum(claims, axis=1)
print("Total claims per policyholder: ", total_claims)


Total claims per policyholder:  [45000 40000 36000]


In [4]:
total_claims = np.sum(claims, axis=0)
print(total_claims)

[31000 39000 51000]


In [5]:
avg_claims = np.mean(claims, axis=0)
print(avg_claims)

[10333.33333333 13000.         17000.        ]


In [6]:
high_value_claims = claims[claims> 15000]
print(high_value_claims)

[18000 17000 16000]


In [7]:
data = np.array([
    ["COO1", 5, "Excellent service and friendly staff"],
    ["CO02", 4, "Good product selection but long wait time"],
    ["CO03", 3, "Average experience, checkout was slow"],
    ["CO04", 5, "Loved the disounts!, Will shop again"],
    ["CO05", 2, "Poor customer support, not satisfied"],
    ["CO06", 4, "Good quality but a bit expensive"],
    ["CO07", 1, "Terrible experience, rude staff"],
    ["CO08", 5, "Amazing deals and fast service"],
])

print(data)

[['COO1' '5' 'Excellent service and friendly staff']
 ['CO02' '4' 'Good product selection but long wait time']
 ['CO03' '3' 'Average experience, checkout was slow']
 ['CO04' '5' 'Loved the disounts!, Will shop again']
 ['CO05' '2' 'Poor customer support, not satisfied']
 ['CO06' '4' 'Good quality but a bit expensive']
 ['CO07' '1' 'Terrible experience, rude staff']
 ['CO08' '5' 'Amazing deals and fast service']]


In [8]:
ratings = data[:,1].astype(int)
print(f"Total Feedback Entries: {len(ratings)}: ")

Total Feedback Entries: 8: 


In [11]:
 average_ratings = np.mean(ratings)
 print(f"Average Customer Ratings: {average_ratings:.2f}")

Average Customer Ratings: 3.62


In [12]:
highest_rating = np.max(ratings)
print(f"Highest Rating Received: {highest_rating}")

Highest Rating Received: 5


In [13]:
loweset_rating = np.min(ratings)
print(f"Lowest Rating Received: {loweset_rating}")

Lowest Rating Received: 1


In [ ]:
unique_ratings, rating_counts = np.unique(ratings, return_counts=True)

In [ ]:
feedback_comments = data [:, 2]


print("\n**Customer Feedback Analysis Summary**")
print()

print("**Ratings Distribution")
print()
for rating, count in zip(unique_ratings, rating_counts):
    print(f"Rating {rating}: {count} customers")

In [ ]:
policy_data = np.array([
    [1001, 12000, 500000, 5000],
    [1002, 15000, 750000, 7000],
    [1003, 18000, 1000000, 10000],
    [1004, 20000, 1200000, 12000],
    [1005, 25000, 1500000, 15000],
])

col = ["Policy Number", "Premium Amount", "Insured Amount", "Claim Amount"]
print("Original Policyholder Data:")
print(policy_data)
df = pd.DataFrame(policy_data, columns=col)
print(df_before)